//-------------------------Auth----------------------------//
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAILED = 'LOGIN_WITH_EMAIL_FAILED';
//--------------------------Category ------------------------//
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const UPDATE_CATEGORY_STATUS_SUCCESS = 'UPDATE_CATEGORY_STATUS_SUCCESS';
export const UPDATE_CATEGORY_STATUS_FAILED = 'UPDATE_CATEGORY_STATUS_FAILED';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';
export const FETCH_CATEGORY_TYPES_SUCCESS = 'FETCH_CATEGORY_TYPES_SUCCESS';
export const FETCH_CATEGORY_TYPES_FAILED = 'FETCH_CATEGORY_TYPES_FAILED';
//---------------------------Sub Category ---------------------//
export const ADD_SUB_CATEGORY_SUCCESS = 'ADD_SUB_CATEGORY_SUCCESS';
export const ADD_SUB_CATEGORY_FAILED = 'ADD_SUB_CATEGORY_FAILED';
export const FETCH_SUB_CATEGORY_SUCCESS = 'FETCH_SUB_CATEGORY_SUCCESS';
export const FETCH_SUB_CATEGORY_FAILED = 'FETCH_SUB_CATEGORY_FAILED';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAILED = 'DELETE_SUB_CATEGORY_FAILED';
export const UPDATE_SUB_CATEGORY_STATUS_SUCCESS =
  'UPDATE_SUB_CATEGORY_STATUS_SUCCESS';
export const UPDATE_SUB_CATEGORY_STATUS_FAILED =
  'UPDATE_SUB_CATEGORY_STATUS_FAILED';
export const GET_SUB_CATEGORY_BY_ID_SUCCESS = 'GET_SUB_CATEGORY_BY_ID_SUCCESS';
export const GET_SUB_CATEGORY_BY_ID_FAILED = 'GET_SUB_CATEGORY_BY_ID_FAILED';
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS';
export const UPDATE_SUB_CATEGORY_FAILED = 'UPDATE_SUB_CATEGORY_FAILED';
export const FETCH_SUB_CATEGORY_TYPES_SUCCESS =
  'FETCH_SUB_CATEGORY_TYPES_SUCCESS';
export const FETCH_SUB_CATEGORY_TYPES_FAILED =
  'FETCH_SUB_CATEGORY_TYPES_FAILED';

//-----------------------Vendors -----------------------------//
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_FAILED = 'GET_VENDORS_FAILED';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_FAILED = 'ADD_VENDOR_FAILED';
export const FETCH_VENDOR_DETAILS_SUCCESS = 'FETCH_VENDOR_DETAILS_SUCCESS';
export const FETCH_VENDOR_DETAILS_FAILED = 'FETCH_VENDOR_DETAILS_FAILED';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILED = 'DELETE_VENDOR_FAILED';
export const GET_VENDOR_BY_ID_SUCCESS = 'GET_VENDOR_BY_ID_SUCCESS';
export const GET_VENDOR_BY_ID_FAILED = 'GET_VENDOR_BY_ID_FAILED';

//---------------------Product--------------------------------//
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';

//--------------------Coupon----------------------------------//
export const VALIDATE_COUPON_CODE_SUCCESS = 'VALIDATE_COUPON_CODE_SUCCESS';
export const VALIDATE_COUPON_CODE_FAILED = 'VALIDATE_COUPON_CODE_FAILED';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_FAILED = 'ADD_COUPON_FAILED';
export const FETCH_COUPON_SUCCESS = 'FETCH_COUPON_SUCCESS';
export const FETCH_COUPON_FAILED = 'FETCH_COUPON_FAILED';
export const UPDATE_COUPON_STATUS_SUCCESS = 'UPDATE_COUPON_STATUS_SUCCESS';
export const UPDATE_COUPON_STATUS_FAILED = 'UPDATE_COUPON_STATUS_FAILED';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAILED = 'DELETE_COUPON_FAILED';
export const GET_COUPON_DETAILS_BY_ID_SUCCESS =
  'GET_COUPON_DETAILS_BY_ID_SUCCESS';
export const GET_COUPON_DETAILS_BY_ID_FAILED =
  'GET_COUPON_DETAILS_BY_ID_FAILED';
export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS';
export const UPDATE_COUPON_FAILED = 'UPDATE_COUPON_FAILED';
