//-------------------------Auth----------------------------//
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAILED = 'LOGIN_WITH_EMAIL_FAILED';
//--------------------------Category ------------------------//
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const UPDATE_CATEGORY_STATUS_SUCCESS = 'UPDATE_CATEGORY_STATUS_SUCCESS';
export const UPDATE_CATEGORY_STATUS_FAILED = 'UPDATE_CATEGORY_STATUS_FAILED';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';
export const FETCH_CATEGORY_TYPES_SUCCESS = 'FETCH_CATEGORY_TYPES_SUCCESS';
export const FETCH_CATEGORY_TYPES_FAILED = 'FETCH_CATEGORY_TYPES_FAILED';
//---------------------------Sub Category ---------------------//
export const ADD_SUB_CATEGORY_SUCCESS = 'ADD_SUB_CATEGORY_SUCCESS';
export const ADD_SUB_CATEGORY_FAILED = 'ADD_SUB_CATEGORY_FAILED';
export const FETCH_SUB_CATEGORY_SUCCESS = 'FETCH_SUB_CATEGORY_SUCCESS';
export const FETCH_SUB_CATEGORY_FAILED = 'FETCH_SUB_CATEGORY_FAILED';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAILED = 'DELETE_SUB_CATEGORY_FAILED';
export const UPDATE_SUB_CATEGORY_STATUS_SUCCESS =
  'UPDATE_SUB_CATEGORY_STATUS_SUCCESS';
export const UPDATE_SUB_CATEGORY_STATUS_FAILED =
  'UPDATE_SUB_CATEGORY_STATUS_FAILED';
export const GET_SUB_CATEGORY_BY_ID_SUCCESS = 'GET_SUB_CATEGORY_BY_ID_SUCCESS';
export const GET_SUB_CATEGORY_BY_ID_FAILED = 'GET_SUB_CATEGORY_BY_ID_FAILED';
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS';
export const UPDATE_SUB_CATEGORY_FAILED = 'UPDATE_SUB_CATEGORY_FAILED';
